# producer
version: '2'

services:
  producer:
    image: noxtech-producer
    container_name: noxtech-producer
    build: ./build/docker
    ports:
      - "8081:8080"
    environment:
      - RABBIT_MQ_IP=${RABBIT_MQ_IP}